spring:
  application:
    name: api
    security:
      jwt:
        secret: "zM4y6Q1maI/mvNG7N3/pJyGR+2G0+pH/EbhEgZgX6AA=" # remove from here on prod, and make it double the size openssl rand -base64 64
        expiration-seconds:
          access-token: 900
          refresh-token: 1209600
        cookie:
          name: refresh_token
          path: /api/v1/auth
          same-site: Lax
          secure: false   # set to true (and same-site: None) in prod over https
  jmx:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  mvc:
    servlet:
      path: /api/v1