ALTER TABLE notes ADD COLUMN subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE;
ALTER TABLE notes ADD COLUMN topic_id   UUID REFERENCES topics(id) ON DELETE SET NULL;

ALTER TABLE mcqs ADD COLUMN subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE;
ALTER TABLE mcqs ADD COLUMN topic_id   UUID REFERENCES topics(id) ON DELETE SET NULL;
