services:
  postgres:
    image: 'postgres:18'
    environment:
      POSTGRES_DB: 'recallr'
      POSTGRES_PASSWORD: '123@tinRoy'
      POSTGRES_USER: 'atinroy'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: